// <auto-generated />
using Eyedrop.MineXplorer.Types;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eyedrop.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20260222152358_SpeakNullable")]
    partial class SpeakNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Eyedrop.MineXplorer.Types.Ghost", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSpeak")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Scene")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("Ghosts");
                });

            modelBuilder.Entity("Eyedrop.MineXplorer.Types.User", b =>
                {
                    b.Property<ulong>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Banned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GhostName")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("LastPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastSpawnData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tokens")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("GhostName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Eyedrop.MineXplorer.Types.User", b =>
                {
                    b.HasOne("Eyedrop.MineXplorer.Types.Ghost", "Ghost")
                        .WithMany()
                        .HasForeignKey("GhostName");

                    b.Navigation("Ghost");
                });
#pragma warning restore 612, 618
        }
    }
}
