// <auto-generated />
using Eyedrop.ADU.Types;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eyedrop.Migrations.ADU
{
    [DbContext(typeof(ADUContext))]
    [Migration("20260224114956_ADUCreate")]
    partial class ADUCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Eyedrop.ADU.Types.Upload", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Uploads");
                });
#pragma warning restore 612, 618
        }
    }
}
